### ISSUE TITLE
Where does the content of the mapDispatchToProps go?

### ISSUE THREAD

**Issue by caedes** [alexnm/re-ducks#8]
Hi!

I'm just wondering where I can put `mapDispatchToProps` of the ⚛️Redux `connect`. I want to unit test it, and can't just write it down as:

```javascript
import { connect } from 'react-redux';

import MyComponent from './component';
import { actions, selectors } from './redux';

return connect(selectors.adSenseOptions, {
  myAction: actions.myAction01
})(MyComponent);
```

Maybe it makes sense to put it into the `selectors.js`, because it is **a selection** of some of the actions.

```javascript
import { connect } from 'react-redux';

import MyComponent from './component';
import { actions, selectors } from './redux';

return connect(selectors.adSenseOptions, ...actions)(MyComponent);
```

What do you think?

**Comment by alexnm** [comment]
I wouldn't introduce a dependency from the components to the state management layer. Testing the component without the connect function is a bit of a problem. I suggest you either export both the "connected" component as well as the regular component, so you can unit test it separately.
